# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get changed files
        id : get-changed-files
        uses : yskeee/gh-action-get-changed-files@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output all changed files
        run: echo ${{ steps.get-changed-files.outputs.all }}

      - name: Output added files
        run: echo ${{ steps.get-changed-files.outputs.added }}

      - name: Output modified files
        run: echo ${{ steps.get-changed-files.outputs.modified }}

      - name: Output renamed files
        run: echo ${{ steps.get-changed-files.outputs.renamed }}

      - name: Output removed files
        run: echo ${{ steps.get-changed-files.outputs.removed }}

      - name: echo if contains packages/common
        if: ${{ contains(steps.get-changed-files.outputs.all, 'packages/common') || contains(steps.get-changed-files.outputs.removed, 'packages/common') }}
        run: echo 'packages/common/* has changed'

      - name: echo if contains packages/frontend
        if: ${{ contains(steps.get-changed-files.outputs.all, 'packages/frontend') || contains(steps.get-changed-files.outputs.removed, 'packages/frontend') }}
        run: echo 'packages/frontend/* has changed'

      - name: echo if contains packages/backend
        if: ${{ contains(steps.get-changed-files.outputs.all, 'packages/backend') || contains(steps.get-changed-files.outputs.removed, 'packages/backend') }}
        run: echo 'packages/backend/* has changed'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
